name: Export

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight UTC
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Babashka
        env:
          BABASHKA_VERSION: 1.12.208
        run: |
          curl -sLO https://github.com/babashka/babashka/releases/download/v${{env.BABASHKA_VERSION}}/babashka-${{env.BABASHKA_VERSION}}-linux-amd64.tar.gz
          sudo tar -xzf babashka-1.12.208-linux-amd64.tar.gz -C /usr/local/bin --strip-components=0

      - name: Run export script
        run: ./bin/export-csv

      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          file_pattern: "data/*.csv"
          commit_message: "chore: automatic csv export"
